# Generated by Django 4.2.7 on 2026-01-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Clothing product', 'verbose_name_plural': 'Clothing products'},
        ),
        migrations.AddField(
            model_name='product',
            name='generated_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='AI prompt for generating images'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Number of items currently in stock for this product variant'),
        ),
    ]
